Yumi_RIGHT:
  root_name: "yumi_body"
  tip_name: "gripper_r_base"
  joint_location: [3, 5, 7, 9, 11, 13, 15]

Yumi_LEFT:
  root_name: "yumi_body"
  tip_name: "gripper_l_base"
  joint_location: [2, 4, 6, 8, 10, 12, 14]
